//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_page.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Freshers_Training2022Entities : DbContext
    {
        public Freshers_Training2022Entities()
            : base("name=Freshers_Training2022Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MM_Carts> MM_Carts { get; set; }
        public virtual DbSet<MM_Categories> MM_Categories { get; set; }
        public virtual DbSet<MM_Contact> MM_Contact { get; set; }
        public virtual DbSet<MM_Orders> MM_Orders { get; set; }
        public virtual DbSet<MM_Payment> MM_Payment { get; set; }
        public virtual DbSet<MM_Products> MM_Products { get; set; }
        public virtual DbSet<MM_User> MM_User { get; set; }
        public virtual DbSet<MM_Admin> MM_Admin { get; set; }
    }
}
